src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>IF( 
Activate_Application_Date__c &lt;=  TODAY() &amp;&amp; End_Application_Date__c  &gt;=  TODAY(), &quot;Active&quot;, &quot;Inactive&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Active&quot; if applications for this term are currently open. &quot;Inactive&quot; otherwise.</inlineHelpText>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Census_Date__c</fullName>
        <formula>Term_Start_Date__c + 10</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Census Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <inlineHelpText>Start date for this term.</inlineHelpText>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ethos__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ethos__c</referenceTo>
        <relationshipLabel>Applications (Academic Program)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Clone_Comment__c</fullName>
        <description>Explanation on the reason for creating the application record clone</description>
        <label>Clone Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Clone_Count__c</fullName>
        <description>The number of times an application has been cloned</description>
        <label>Clone Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Term_of_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Term of Entry</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginalApplication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains a reference to SOURCE application</description>
        <inlineHelpText>Contains a reference to SOURCE application</inlineHelpText>
        <label>Original Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>HistoryApplications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Power of One</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities with Academic Program</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Academic_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to EASY Term Object</description>
        <inlineHelpText>EASY Term Object</inlineHelpText>
        <label>Academic Term</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the EASY Application object</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Key__c</fullName>
        <description>A unique external ID text field which determines whether an Interaction will create a new Opportunity or edit an existing Opportunity. Built using the Contact’s 18-digit ID, Career, Term’s 15-digit ID, and Recruitment/Academic Program’s 15-digit ID (if applicable) to ensure uniqueness and support of both a central and decentral recruitment process. Set by the Interactions Processor.</description>
        <externalId>true</externalId>
        <label>Opportunity Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>It&apos;s the Power of One (you&apos;re welcome!)</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pwned!</inlineHelpText>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OriginalOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contains a reference to SOURCE opportunity: ONU-222</description>
        <inlineHelpText>Contains a reference to SOURCE opportunity: ONU-222</inlineHelpText>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>HistoricalOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status_picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Pick One (Default)</fullName>
                </value>
                <value>
                    <fullName>Chose Another University</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Multiple Programs Chosen</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>No Longer Interested</fullName>
                </value>
                <value>
                    <fullName>Non-Start</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Program Not Offered</fullName>
                </value>
                <value>
                    <fullName>Traditional Student</fullName>
                </value>
                <value>
                    <fullName>Fake/Invaid Information</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Rolled</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Needs Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_picklist__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>A checkbox to mark whether or not a Program is active.</description>
        <externalId>true</externalId>
        <inlineHelpText>External code for the program (e.g. SIS ID). This is used for integration with external systems.</inlineHelpText>
        <label>Program Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Historic</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
        <isActive>false</isActive>
        <label>Deposit Waived</label>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
        <isActive>false</isActive>
        <label>Deposit Paid</label>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
        <isActive>false</isActive>
        <label>Deferred</label>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
        <isActive>false</isActive>
        <label>Complete-Pending Review</label>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
        <isActive>false</isActive>
        <label>Complete-Pending Additional Review</label>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
        <isActive>false</isActive>
        <label>Complete-Decision Made</label>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
        <isActive>false</isActive>
        <label>Incomplete</label>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/classes/ApplicationCloneSchedule.cls
/**
 * Created by maxim_elets on 9/24/19.
 * ONU-222;
 */

public with sharing class ApplicationCloneSchedule implements Database.Batchable<sObject>,
                                                                Schedulable,
                                                                Database.Stateful {

//  ApplicationCloneSchedule b = new ApplicationCloneSchedule();
//  String sch = '0 0 1 * * ?'; // This is just like a regular cron job
//  system.schedule('Application Clone(ONU-222)', sch, b);
    public void execute(SchedulableContext param1) {
        ApplicationCloneSchedule b = new ApplicationCloneSchedule();
        Database.executeBatch(b);
    }

    private Set<String> APPLICATION_IGNORE_STATUSES = new Set<String> {
            'Withdrawn', 'Historic', 'Cancelled'
    };
    private String query;
    private Map<Id, Academic_Term__c> priorNextAcademicTermsIds;//what is next term for key Id
    private Map<Id, Academic_Term__c> academicTermsMap; // id  + their record
    public ApplicationCloneSchedule() {
        List<Schema.SObjectField> applicationFields = getAllFields(Application__c.SObjectType);
        List<String> applicationFieldsAsStrings = new List<String>();
        for (Schema.SObjectField f : applicationFields) {
            applicationFieldsAsStrings.add(f.getDescribe().getLocalName());
        }
        List<Schema.SObjectField> opportunityFields = getAllFields(Opportunity.SObjectType);
        List<String> opportunityFieldsAsStrings = new List<String>();
        for (Schema.SObjectField f : opportunityFields) {
            opportunityFieldsAsStrings.add('Opportunity__r.' + f.getDescribe().getLocalName());
        }

        String q = String.format('SELECT {0}, {1}, {3} FROM Application__c WHERE Intended_Term_of_Entry__r.Term_Census_Date__c <= {2} AND Application_Status__c NOT IN :APPLICATION_IGNORE_STATUSES',
                new List<String> {
                        String.join(applicationFieldsAsStrings, ','),
                        String.join(opportunityFieldsAsStrings, ','),
                        'YESTERDAY', //'2019-09-12'
                        String.join(new List<String> {
                                'Intended_Term_of_Entry__r.Term_Census_Date__c',
                                'Opportunity__r.Contact__r.LastName',
                                'Opportunity__r.Academic_Program__r.Program_Code__c',
                                'Opportunity__r.Academic_Program__r.Name'
                        }, ',')//reuiqred fields
                });
        System.debug(q);
        this.query = q;


        //populate academic term order;
        this.priorNextAcademicTermsIds = new Map<Id, Academic_Term__c>();

        List<Academic_Term__c> terms  = [SELECT Id, Name FROM Academic_Term__c WHERE Term_Start_Date__c != NULL ORDER BY Term_Start_Date__c ASC];
        this.academicTermsMap = new Map<Id, Academic_Term__c>(terms);
        Integer iterations = terms.size()-1;
        while (iterations >= 0) {
            Academic_Term__c currentAt = terms.get(iterations);
            if (iterations == terms.size()-1) { //last added term
                this.priorNextAcademicTermsIds.put(currentAt.Id, NULL);
            } else {
                Academic_Term__c nextAt = terms.get(iterations + 1);
                this.priorNextAcademicTermsIds.put(currentAt.Id, nextAt);
            }
            iterations--;
        }
        System.debug(this.priorNextAcademicTermsIds);
    }
    private Boolean onlyClone = false;
    private String cloneComment = '';
    public ApplicationCloneSchedule(String p_query, String p_cloneComment) {
        this.query = p_query;
        this.onlyClone = true;
        this.cloneComment = p_cloneComment;
    }
    public Iterable<sObject> start(Database.BatchableContext ctx) {
        System.debug(this.query);
        return Database.getQueryLocator(this.query);
    }
    public void execute(Database.BatchableContext ctx, List<sObject> scope) {
        Savepoint sp = Database.setSavepoint();
        try {
            System.debug(scope.size());
            List<Application__c> snapshots = new List<Application__c>();
            Map<Id, Application__c> originalApplicationsMap = new Map<Id, Application__c>((List<Application__c>)scope);
            Map<Id, Opportunity> originalOpportunitiesMap = new Map<Id, Opportunity>();//to close
            Map<Id, Integer> cloneCounterMap = new Map<Id, Integer>();
            for (Application__c oa : (List<Application__c>)scope) {
                Integer nextCloneCount = Integer.valueOf(oa.Clone_Count__c != NULL ? (oa.Clone_Count__c + 1) : 1);
                if (nextCloneCount > 2) {
                    oa.Application_Status__c = 'Cancelled';
                } else {
                    //SNAPSHOTS
                    Application__c ha = oa.clone(false, true, false, false);
                    ha.Application_Status__c = 'Historic';
                    ha.OriginalApplication__c = oa.Id;

                    snapshots.add(ha);

                    //ORIGINAL
                    if ( !this.onlyClone && this.priorNextAcademicTermsIds.containsKey(oa.Intended_Term_of_Entry__c)) {
                        oa.Intended_Term_of_Entry__c = this.priorNextAcademicTermsIds.get(oa.Intended_Term_of_Entry__c).Id;
                        if (oa.Intended_Term_of_Entry__c == NULL) {
                            throw new ApplicationCloneScheduleException('Next academic term is not available for record: ' + oa.Id);
                        }
                    }
                    oa.Clone_Count__c = nextCloneCount;
                    oa.Clone_Comment__c = String.isNotBlank(oa.Clone_Comment__c) ? oa.Clone_Comment__c : '';
                    if (String.isBlank(this.cloneComment)) {
                        oa.Clone_Comment__c += '\r\nHISTORY APPLICATION CREATED: Term Census Date = ' + oa.Intended_Term_of_Entry__r.Term_Census_Date__c;
                    } else {
                        oa.Clone_Comment__c = this.cloneComment + '\r\n' + oa.Clone_Comment__c;
                    }

                    if (oa.Opportunity__r != NULL) {
                        originalOpportunitiesMap.put(oa.Opportunity__c, oa.Opportunity__r);
                        cloneCounterMap.put(oa.Opportunity__c, Integer.valueOf(oa.Clone_Count__c));
                    }

                }
            }
            //insert new opportunities
            Map<Id, Opportunity> historicalOpportunitiesMap = new Map<Id, Opportunity>(); // to insert
            for (Opportunity oo : originalOpportunitiesMap.values()) {
                System.debug(oo.Academic_Term__c);
                System.debug(this.priorNextAcademicTermsIds);
                if (!this.onlyClone) {
                    oo.Academic_Term__c = this.priorNextAcademicTermsIds.get(oo.Academic_Term__c).Id;
                    oo.Name = String.format('{0} {1} {2} {}', new List<String>{
                            oo.Contact__r.LastName,
                            String.isBlank(oo.Academic_Program__r.Program_Code__c) ? oo.Academic_Program__r.Name : oo.Academic_Program__r.Program_Code__c,
                            this.academicTermsMap.get(oo.Academic_Term__c).Name
                    }
                    );
                }
                oo.Status_picklist__c = 'Open';
                if (oo.Amount != NULL) {
                    oo.Amount = oo.Amount - (oo.Amount*33/100);// TODO: based on clone count;
                }


                //open new opportunity
                Opportunity ho = oo.clone(false, true, false, false);
                //close old opportunity
                ho.Status_picklist__c = 'Lost';
                ho.Status_Reason__c = 'Rolled';
                ho.OriginalOpportunity__c = oo.Id;
                ho.Opportunity_Key__c = NULL;
                ho.Name += 'Historic_' + cloneCounterMap.get(oo.Id);
                historicalOpportunitiesMap.put(oo.Id, ho);
                System.debug(ho.Id);
            }
            //update original opportunities
            Database.update(originalOpportunitiesMap.values());
            //insert historical opportunities
            Database.insert(historicalOpportunitiesMap.values());

            //update opportunity on historical applicaitons
            for (Application__c ha : snapshots) {
                if (historicalOpportunitiesMap.containsKey(ha.Opportunity__c)) {
                    ha.Opportunity__c = historicalOpportunitiesMap.get(ha.Opportunity__c).Id;
                } else {

                }

            }
            //insert historical applications
            Database.insert(snapshots);

            //update original applications
            Database.update(scope);
        } catch (Exception e) {
            Database.rollback(sp);
            throw new ApplicationCloneScheduleException(e.getMessage() + ' - ' + e.getStackTraceString());
        }
    }

    public void finish(Database.BatchableContext ctx) {
    }


    /**
    * @description Get all fields of a SObject.
    * @param p_sobjectType Schema.SObjectType of a SObject tgetAllFieldso get writable fields.
    * @return List of Schema.SObjectField writable fields.
    */
    public static final Set<String> FIELDS_TO_IGNORE = new Set<String> {
            'LastViewedDate', 'LastReferencedDate', 'LastActivityDate', 'IqScore' };
    private static List<Schema.SObjectField> getAllFields(Schema.SObjectType p_sobjectType) {

        return SchemaUtils.getAllFields(p_sobjectType, FIELDS_TO_IGNORE);
    }

    public class ApplicationCloneScheduleException extends Exception { }

}