src/objects/Academic_Term__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>IF( 
Activate_Application_Date__c &lt;=  TODAY() &amp;&amp; End_Application_Date__c  &gt;=  TODAY(), &quot;Active&quot;, &quot;Inactive&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Active&quot; if applications for this term are currently open. &quot;Inactive&quot; otherwise.</inlineHelpText>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Census_Date__c</fullName>
        <formula>Term_Start_Date__c + 10</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term Census Date</label>
        <type>Date</type>
    </fields>
    <label>Academic Term</label>
    <nameField>
        <label>Academic Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Academic Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Ethos__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Academic Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ethos__c</referenceTo>
        <relationshipLabel>Applications (Academic Program)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Clone_Count__c</fullName>
        <description>The number of times an application has been cloned</description>
        <label>Clone Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Term_of_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intended Term of Entry</label>
        <referenceTo>Academic_Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The Power of One</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Academic_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The official plan or program the individual applies for. A lookup to Program with a filter criteria of Record Type = Academic Program.</description>
        <inlineHelpText>The official plan or program the individual applies for.</inlineHelpText>
        <label>Academic Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Academic Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities with Academic Program</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the EASY Application object</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Connects this Opportunity to a Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>It&apos;s the Power of One (you&apos;re welcome!)</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pwned!</inlineHelpText>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>An object for housing recruitment and academic program records. There are two record types: Recruitment Programs and Academic Programs.</description>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>A checkbox to mark whether or not a Program is active.</description>
        <externalId>true</externalId>
        <inlineHelpText>External code for the program (e.g. SIS ID). This is used for integration with external systems.</inlineHelpText>
        <label>Program Code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Application_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Started</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Historic</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Deposit Waived</fullName>
        <isActive>false</isActive>
        <label>Deposit Waived</label>
    </customValue>
    <customValue>
        <fullName>Deposit Paid</fullName>
        <isActive>false</isActive>
        <label>Deposit Paid</label>
    </customValue>
    <customValue>
        <fullName>Deferred</fullName>
        <isActive>false</isActive>
        <label>Deferred</label>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Review</fullName>
        <isActive>false</isActive>
        <label>Complete-Pending Review</label>
    </customValue>
    <customValue>
        <fullName>Complete-Pending Additional Review</fullName>
        <isActive>false</isActive>
        <label>Complete-Pending Additional Review</label>
    </customValue>
    <customValue>
        <fullName>Complete-Decision Made</fullName>
        <isActive>false</isActive>
        <label>Complete-Decision Made</label>
    </customValue>
    <customValue>
        <fullName>Incomplete</fullName>
        <isActive>false</isActive>
        <label>Incomplete</label>
    </customValue>
    <masterLabel>Application Status</masterLabel>
</GlobalValueSet>

src/classes/ApplicationCloneController.cls
/**
 * Created by maxim_elets on 10/23/19.
 */

public with sharing class ApplicationCloneController {
	public Id applicationId {get; set; }
	public Application__c application { get; set; }
	public Boolean cloneNotAvailable { get; set; }
	public String cloneComment { get; set; }
	public Boolean cloneInProgress { get; set; }
	public ApplicationCloneController(ApexPages.StandardController std) {
		this.applicationId = std.getId();
		this.cloneNotAvailable = false;
		this.cloneComment = '';
		this.cloneInProgress = this.checkIfCloneInProgress();

		List<Application__c> applications = Database.query(this.getApplicationQuery());
		if (applications.size() > 0) {
			this.application = applications.get(0);
		} else {
			this.cloneNotAvailable = true;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
					'\'Withdrawn\', \'Historic\', \'Cancelled\' applications can\'t be cloned. Also application can be cloned only 2 times.'));
		}
	}

	public Boolean getHasMessages() {
		return  ApexPages.hasMessages();
	}

	public Boolean getHasErrorMessages() {
		return  ApexPages.hasMessages(ApexPages.Severity.ERROR);
	}

	public void doClone() {
		if (this.checkIfCloneInProgress()) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
					'There is another clone process was not finished yet. Please try again soon, or please check clone process status in Setup->Apex Jobs'));
			System.debug('JOB');
		} else {
			ApplicationCloneSchedule b = new ApplicationCloneSchedule(this.getApplicationQuery(), String.isNotBlank(this.cloneComment) ? this.cloneComment : 'Manually Cloned by ' + UserInfo.getName());
			Id jobId = Database.executeBatch(b);
			this.setCookie(jobId);
			this.cloneInProgress = true;
		}
	}
	@TestVisible
	private Boolean checkIfCloneInProgress() {
		Set<String> completedStatuses = new Set<String> {
				'Completed', 'Failed'
		};
		Id jobId = this.getCurrentCronIdFromCookie();
		if (jobId != NULL) {
			AsyncApexJob aaj = this.getApexJobStatusById(jobId);
			return !completedStatuses.contains(aaj.Status);
		}

		return false;
	}
	private Set<String> APPLICATION_IGNORE_STATUSES = new Set<String> {
			'Withdrawn', 'Historic', 'Cancelled'
	};
	private String getApplicationQuery() {
		List<Schema.SObjectField> applicationFields = SchemaUtils.getAllFields(Application__c.SObjectType, NULL);
		List<String> applicationFieldsAsStrings = new List<String>();
		for (Schema.SObjectField f : applicationFields) {
			applicationFieldsAsStrings.add(f.getDescribe().getLocalName());
		}
		List<Schema.SObjectField> opportunityFields = SchemaUtils.getAllFields(Opportunity.SObjectType, NULL);
		List<String> opportunityFieldsAsStrings = new List<String>();
		for (Schema.SObjectField f : opportunityFields) {
			opportunityFieldsAsStrings.add('Opportunity__r.' + f.getDescribe().getLocalName());
		}

		String q = String.format('SELECT {0}, {1}, {3} FROM Application__c WHERE Id = {2} AND Application_Status__c NOT IN :APPLICATION_IGNORE_STATUSES AND (Clone_Count__c = NULL OR Clone_Count__c < 2)',
				new List<String> {
						String.join(applicationFieldsAsStrings, ','),
						String.join(opportunityFieldsAsStrings, ','),
						'\''+ this.applicationId + '\'', //'2019-09-12'
						String.join(new List<String> {
								'Intended_Term_of_Entry__r.Term_Census_Date__c',
								'Opportunity__r.Contact__r.LastName',
								'Opportunity__r.Academic_Program__r.Program_Code__c',
								'Opportunity__r.Academic_Program__r.Name'
						}, ',')//reuiqred fields
				});
		System.debug(q);
		return q;
	}


	private Id getCurrentCronIdFromCookie() {
		Cookie cookieMap = ApexPages.currentPage().getCookies().get('application_clone_map');
		if (cookieMap != NULL) {
			Map<Id, Id> data = (Map<Id, Id>)JSON.deserialize(cookieMap.getValue(), Map<Id, Id>.class);
			if (data.containsKey(this.applicationId)) {
				return data.get(this.applicationId);
			}
		}
		return NULL;
	}
	private void setCookie(Id p_jobId) {
		Cookie cookieMap = ApexPages.currentPage().getCookies().get('application_clone_map');
		Map<Id, Id> data;
		if (cookieMap == NULL) {
			data = new Map<Id, Id>();
			data.put(this.applicationId, p_jobId);
		} else {
			// If this isn't the first time the user is accessing the page
			// create a new cookie, incrementing the value of the original count by 1
			data = (Map<Id, Id>)JSON.deserialize(cookieMap.getValue(), Map<Id, Id>.class);
			data.put(this.applicationId, p_jobId);
		}
		cookieMap = new Cookie('application_clone_map', JSON.serialize(data),NULL,-1,false);

		// Set the new cookie for the page
		ApexPages.currentPage().setCookies(new Cookie[]{ cookieMap });
	}

	private AsyncApexJob getApexJobStatusById(Id p_jobId) {
		return [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob WHERE Id =: p_jobId ];
	}
}